<?php
namespace Amon\Request;

use Amon\Config\BaseConfig;

/**
 * Test class for Request.
 * Generated by PHPUnit on 2012-02-23 at 00:10:37.
 */
class RequestTest extends \PHPUnit_Framework_TestCase
{
    protected $_wrongConfig;
    protected $_data;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->_wrongConfig = array(
            'host' => 'http://1.1.1.1',
            'port' => 999,
        );
        $this->_data = array(
            'message' => 'test',
            'tags'    => 'tag'
        );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Amon\Request\Request::__construct
     */
    public function testClassConstruct()
    {
        $object = new Request(new BaseConfig());
        $this->assertInstanceOf('Amon\\Request\\RequestInterface',$object);
    }

    /**
     * @covers Amon\Request\Request::doRequest
     */
    public function testDoRequestWithWronParams()
    {
        $config = new BaseConfig($this->_wrongConfig);
        $object = new Request($config);

        $this->setExpectedException('Amon\\Exception\\NetworkErrorException');

        $object->doRequest($this->_data);
    }

    /**
     * @covers Amon\Request\Request::doRequest
     */
    public function testDoRequestWithWronType()
    {
        $config = new BaseConfig($this->_wrongConfig);
        $object = new Request($config);

        $this->setExpectedException('Amon\\Exception\\UnknownLogTypeException');

        $object->doRequest($this->_data, 'wrong');

    }
}

?>
