<?php
namespace Amon;

use Amon\Request\MockRequest;

/**
 * Test class for AmonLogger.
 * Generated by PHPUnit on 2012-02-22 at 22:03:47.
 */
class AmonLoggerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var AmonLogger
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $request = new MockRequest();

        $this->object = new AmonLogger($request);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Amon\AmonLogger::__construct
     */
    public function testClassConstruct()
    {
        $this->assertInstanceOf('Amon\\Interfaces\\LoggerInterface',$this->object);
    }
    /**
     * log message with one tag
     *
     * @covers Amon\AmonLogger::log
     * @covers Amon\AmonLogger::_createMessage
     */
    public function testLogOneTag()
    {
        $result = $this->object->log('test','key');
        $this->assertEquals(true, $result);
    }

    /**
     * log message with array of tags
     *
     * @covers Amon\AmonLogger::log
     * @covers Amon\AmonLogger::_createMessage
     */
    public function testLogTagsArray()
    {
        $result = $this->object->log('test',array('key','key2'));
        $this->assertEquals(true, $result);
    }

    /**
     * log message without tags
     *
     * @covers Amon\AmonLogger::log
     * @covers Amon\AmonLogger::_createMessage
     */
    public function testLogWithoutArray()
    {
        $result = $this->object->log('test');
        $this->assertEquals(true, $result);
    }
}
?>
